import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard-Ut-Api</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Rest-Api with Next.js!
        </h1>

        <div className={styles.grid}>
          <a href="http://localhost:3000/api/courses" className={styles.card}>
            <h2>Static API Routes &rarr;</h2>
            <p>API routes provide a solution to build your API with Next.js.</p>
          </a>

          <a href="http://localhost:3000/api/nested-static/first" className={styles.card}>
            <h2>Static Nested API Routes &rarr;</h2>
            <p>Nested resources are common in real life, and when you're a programmer working on RESTful APIs you may have noticed that there are often trade-offs when it comes to formatting the routes of nested resources.</p>
          </a>

          <a href="http://localhost:3000/api/nested-dynamic/cobol" className={styles.card}>
            <h2>Dynamic Nested API Routes &rarr;</h2>
            <p>Nested resources are common in real life, and when you're a programmer working on RESTful APIs you may have noticed that there are often trade-offs when it comes to formatting the routes of nested resources.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        {<a
          href="https://github.com/franjmr/nextjsRestApi"
          target="_blank"
          rel="noopener noreferrer"
        >
          franjmr github. Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>}
      </footer>
    </div>
  )
}
